### ISSUE TITLE
How to promote packages

### ISSUE THREAD

**Issue by jjwilliams42** [ChaseFlorell/chaseflorell.github.io#2]
Chase, love the post at https://chaseflorell.github.io/devops/2015/08/07/deploying-squirrel.windows-apps-with-octopus-deploy/ ... it got me going using Octopus + Squirrel + WPF. Here are some things I figured out that may help:

The ProductName in the AssemblyInfo is what drives the icon names. There was no clean way that I found to "promote" the same build, until I found this amazing tool: verpatch (https://ddverpatch.codeplex.com/documentation)

By adding this code to deploy.ps1, in UpdateConfiguration (after the cepsun rename), it will change the Product Name from "My WPF Client" to "My WPF Client [Beta/Nightly/Stable]" - or whatever the environment is. Here is the code:

``` powershell
$productName = "My Client"

    if ($environment -ne "stable"){
        #capitalize
        $fixedEnvironment = $environment.Substring(0,1).ToUpper() + $environment.Substring(1).ToLower()
        $productName = $productName + " " + $fixedEnvironment
    }

    # Promote / Change product name of application
    Write-Host "Promoting application to Delta Client $environmentFixed"
    exec {
        & "$currentDir\tools\verpatch\verpatch.exe" "$currentDir\website\Application Files\DeltaClient.WPF.exe" /s product "$productName"
    }
    Write-Host "Successfully promoted application to Delta Client $environmentFixed"
```

You also need to include the verpatch.exe somewhere (mine is in tools\verpatch).

This was the final step that did away with my "build per branch" of "develop/master/beta", and let me build once and deploy everywhere (with the same package / binaries). Hope this helps!

Thanks for all your initial hard work on getting Squirrel + WPF + Octopus going!

**Comment by jjwilliams42** [comment]
Also note that I check if $environment -ne "stable" ... that is so it will by default (for stable / production) leave us with an Icon / ProductName of "My Client".

**Comment by ChaseFlorell** [comment]
Hey, that's super cool.
That was a feature request that I had sent to Paul, but didn't seem to go anywhere. I'm glad you found a way to make it all come together!
